# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=64)),
                ('incoming', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
